name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # 允许手动触发

env:
  REGISTRY: docker.io
  SOURCE_IMAGE: vevc/fml
  TARGET_IMAGE: whggo/aaaa # 修改为您的实际镜像名称

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with latest tag only
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TARGET_IMAGE }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          cache-from: type=registry,ref=${{ env.SOURCE_IMAGE }}
          cache-to: type=inline,mode=max

      - name: Verify push success
        run: |
          echo "Successfully pushed ${{ env.TARGET_IMAGE }}:latest to Docker Hub"
